POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 123,
  "details": "É novo",
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/3f8b949f-51d5-4920-8cd1-d05e232292d4/attendees
Content-Type: application/json

{
  "name": "Rafael Neves",
  "email": "rafael3s@gmail.com"
}

###

GET http://localhost:3333/events/3f8b949f-51d5-4920-8cd1-d05e232292d4

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/3/check-in

###

GET http://localhost:3333/events/3f8b949f-51d5-4920-8cd1-d05e232292d4/attendees?query=Rafael